version: '3.9'

services:
  app:
    build: .
    container_name: hospital-middleware-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      PORT: 3000
      DB_PATH: /data/hospital_middleware.db
      HIS_BASE_URL: https://hospital-a.api.co.th
      USE_MOCK_HIS: "true"
    volumes:
      - app-data:/data
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: hospital-middleware-db
    environment:
      POSTGRES_DB: hospital_middleware
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  app-data:
  db-data:
